version: 2
updates:
- package-ecosystem: github-actions
  commit-message:
    include: scope
  directory: /
  schedule:
    interval: monthly
  groups:
    github-actions:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: docker
  commit-message:
    include: scope
  directory: /
  schedule:
    interval: monthly
  groups:
    docker:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: gomod
  commit-message:
    include: scope
  directory: /
  schedule:
    interval: monthly
  groups:
    gomod:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
