builds:
- id: lagoon-opensearch-sync
  binary: lagoon-opensearch-sync
  main: ./cmd/lagoon-opensearch-sync
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

changelog:
  use: github-native

sboms:
- artifacts: archive

signs:
- cmd: cosign
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  args:
  - "sign-blob"
  - "--output-signature=${signature}"
  - "--output-certificate=${certificate}"
  - "${artifact}"
  - "--yes"
  artifacts: checksum

dockers:
- ids:
  - lagoon-opensearch-sync
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - "--build-arg=BINARY=lagoon-opensearch-sync"
  - "--platform=linux/amd64"
- ids:
  - lagoon-opensearch-sync
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--build-arg=BINARY=lagoon-opensearch-sync"
  - "--platform=linux/arm64/v8"

docker_manifests:
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-arm64v8"
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:latest"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/lagoon-opensearch-sync:v{{ .Version }}-arm64v8"

docker_signs:
- args:
  - "sign"
  - "${artifact}@${digest}"
  - "--yes"
  artifacts: all
  output: true
