name: Lint
on: pull_request
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=180s
        # temporarily pin the linter version until
        # https://github.com/golangci/golangci-lint/issues/3862 is fixed
        version: v1.52.2
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v5
